django_mini_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, home_view
from .views import UserCreateView, UserCreateDoneTV, NaverMap, NaverMapCenter
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', HomeView.as_view(), name="home"),
    path('', home_view, name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    #계정 생성 완료됐다는 메세지 보여줌
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('naver_map/hospital', NaverMap.as_view(), name="naver_map"),
    path('naver_map/center', NaverMapCenter.as_view(), name="naver_map_center"),
    path('summernote/', include('django_summernote.urls')),
    path('Account/', include('Account.urls')),
    path('pet/', include('pet.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name="pet"
urlpatterns = [
    path('create_post/',views.PetPostCreate.as_view(), name="create_post"),
    path('board/', views.BoardView.as_view(), name="board"),
    path('board/<int:pk>/', views.PetPostDetail.as_view(), name='post_deatil'),
    path('board/update_post/<int:pk>/',views.PetPostUpdate.as_view(), name = 'post_update'),
    path('board/<str:slug>/', views.pet_post_category_page), 
    
    path('animal/', views.AnimalView.as_view(), name="animal"),
    path('animal_detail/<int:pk>/', views.AnimalDetailView.as_view(), name="animal_detail"),
    path('hotel/', views.HotelView.as_view(), name="hotel"),
    path('hotel_detail/<int:pk>/', views.HotelDetailView.as_view(), name="hotel_detail"),
    path('hotel/category/<str:slug>/', views.hotel_category_page),
    path('mybaby/', views.ShowOffPostList.as_view(), name="mybaby"),
    path('mybaby/create_post/',views.ShowoffPostCreate.as_view(), name="mybaby_create_post"),
    path('mybaby/<int:pk>/', views.ShowoffPostDetail.as_view(), name="mybaby_detail"),
    path('mybaby/update_post/<int:pk>/',views.ShowOffPostUpdate.as_view(), name = 'mybaby_update'),
    path('mybaby/<str:slug>/', views.show_off_post_category_page), 
    
    path('recommend/', views.RecommendList.as_view(), name="recommend"),
    path('recommend/create_post/',views.RecommendPostCreate.as_view(), name="recommend_create_post"),
    path('recommend/<int:pk>/', views.RecommendPostDetail.as_view(), name="recommend_detail"),
    path('recommend/update_post/<int:pk>/',views.RecommendPostUpdate.as_view(), name = 'recommend_update'),
    path('recommend/<str:slug>/', views.recommend_post_category_page), 
    
    path('news/', views.NewsList.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetail.as_view(), name="news_detail"),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pet_templates/animal.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 style="color: black; text-align: center;">동물 보호소</h1>
<br>
<div>
    <input id="search" type="search" name="" placeholder="검색어를 입력해주세요." value="">
    <button type="submit" class="btn btn-dark">검색</button>
</div>
<hr>
<section class="blog-list px-3 py-5 p-md-5">
    <div class="container single-col-max-width">
        <div class="item mb-5">
            <div class="row g-3 g-xl-0">
                <div id="img-col" class="col-2 col-xl-3">
                    <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                </div>
                <div class="col" style="margin-right: 30px;">
                    <h3 class="title mb-1"><a class="text-link" href="/animal_detail">강아지</a></h3>
                    <div class="meta mb-1"><span class="date">2일 전</span><span class="comment"><a class="text-link"
                                href="#">8 comments</a></span></div>
                    <div class="intro" style="color: black;">
                        장소 : 경기도
                        <br>
                        품종 : 시바
                        <br>
                        나이 : 3살
                    </div>
                    <a class="text-link" href="/animal_detail">Read more &rarr;</a>
                </div><!--//col-->

                <div id="img-col" class="col-2 col-xl-3">
                    <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                </div>
                <div class="col">
                    <h3 class="title mb-1"><a class="text-link" href="/animal_detail">고양이</a></h3>
                    <div class="meta mb-1"><span class="date">1일 전</span><span class="comment"><a class="text-link"
                                href="#">8 comments</a></span></div>
                    <div class="intro" style="color: black;">
                        장소 : 인천
                        <br>
                        품종 : 코숏
                        <br>
                        나이 : 3살
                    </div>
                    <a class="text-link" href="/animal_detail">Read more &rarr;</a>
                </div><!--//col-->
            </div><!--//row-->
            <br>
            <br>
            <div class="row g-3 g-xl-0">
                <div id="img-col" class="col-2 col-xl-3">
                    <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                </div>
                <div class="col" style="margin-right: 30px;">
                    <h3 class="title mb-1"><a class="text-link" href="/animal_detail">강아지</a></h3>
                    <div class="meta mb-1"><span class="date">2일 전</span><span class="comment"><a class="text-link"
                                href="#">8 comments</a></span></div>
                    <div class="intro" style="color: black;">
                        장소 : 경기도
                        <br>
                        품종 : 시바
                        <br>
                        나이 : 3살
                    </div>
                    <a class="text-link" href="/animal_detail">Read more &rarr;</a>
                </div><!--//col-->

                <div id="img-col" class="col-2 col-xl-3">
                    <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                </div>
                <div class="col">
                    <h3 class="title mb-1"><a class="text-link" href="/animal_detail">고양이</a></h3>
                    <div class="meta mb-1"><span class="date">1일 전</span><span class="comment"><a class="text-link"
                                href="#">8 comments</a></span></div>
                    <div class="intro" style="color: black;">
                        장소 : 인천
                        <br>
                        품종 : 코숏
                        <br>
                        나이 : 3살
                    </div>
                    <a class="text-link" href="/animal_detail">Read more &rarr;</a>
                </div><!--//col-->
            </div><!--//row-->
            <br>
            <br>
            <div class="row g-3 g-xl-0">
                <div id="img-col" class="col-2 col-xl-3">
                    <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                </div>
                <div class="col" style="margin-right: 30px;">
                    <h3 class="title mb-1"><a class="text-link" href="/animal_detail">강아지</a></h3>
                    <div class="meta mb-1"><span class="date">2일 전</span><span class="comment"><a class="text-link"
                                href="#">8 comments</a></span></div>
                    <div class="intro" style="color: black;">
                        장소 : 경기도
                        <br>
                        품종 : 시바
                        <br>
                        나이 : 3살
                    </div>
                    <a class="text-link" href="/animal_detail">Read more &rarr;</a>
                </div><!--//col-->

                <div id="img-col" class="col-2 col-xl-3">
                    <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                </div>
                <div class="col">
                    <h3 class="title mb-1"><a class="text-link" href="/animal_detail">고양이</a></h3>
                    <div class="meta mb-1"><span class="date">1일 전</span><span class="comment"><a class="text-link"
                                href="#">8 comments</a></span></div>
                    <div class="intro" style="color: black;">
                        장소 : 인천
                        <br>
                        품종 : 코숏
                        <br>
                        나이 : 3살
                    </div>
                    <a class="text-link" href="/animal_detail">Read more &rarr;</a>
                </div><!--//col-->
            </div><!--//row-->
        </div><!--//item-->
    </div>
    <!-- 페이지 -->
    <div>
        <nav class="pg_wrap"
            style="text-align: center; position: relative; top: 50%; left: 45%; margin: -150px Opx Opx -200px;">
            <strong class="pg_current">1</strong>
            <a href="#page=2" class="pg_page">2</a>
            <a href="#page=3" class="pg_page">3</a>
            <a href="#page=11" class="pg_page">></a>
            <a href="#page=13" class="pg_page">>></a>
        </nav>
        <ul><a href="{% url 'pet_comm:create_post' %}" class="btn_b01 btn float-end" title="글쓰기">
                <i class="bi bi-pencil-square"></i>글쓰기</a>
        </ul>
    </div>
    <!-- 페이지 -->
</section>
{% endblock main_area %}

templates/pet_templates/animal_detail.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<br>
<br>
<br>
<br>
<br>
<nav>
    <ul>
    </ul>
</nav>

<form method="post">
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container single-col-max-width">
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                        <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" style="width:1000px; height:500px;" alt="image">

                    <div class="col" style="margin-right: 30px;">
                        <h3 class="title mb-1"><a class="text-link" href="/보호소링크">강아지</a></h3>
                        <div class="intro" style="color: black;">
                            <table>
                                    <tr>
                                        <th>색상 : 애쉬그레이</th>
                                    </tr>
                                    <tr>
                                        <th>성별 : 남</th>
                                    </tr>
                                    <tr>
                                        <th>출생년도 : 2020</th>                                            
                                    </tr>
                                    <tr>
                                        <th>발견장소 : 독산역</th>                                            
                                    </tr>
                                    <tr>
                                        <th>접수일자 : 2022-12-20</th>                                            
                                    </tr>
                                    <tr>
                                        <th>특징 : 귀여움</th>                                            
                                    </tr>
                                    <tr>
                                        <th>보호센터 : 독산보호센터</th>                                            
                                    </tr>
                                    <tr>
                                        <th>보호소 전화번호 : 031-123-4567</th>                                            
                                    </tr>
                                    <tr>
                                        <th>보호소위치 : 경기도</th>
                                    </tr>
                                </table>
                        </div>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->         
        </div>
    </section>
</form>
{% endblock main_area %}

templates/pet_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-kr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicons -->
    <link href="{%static 'assets/img/favicon.png'%}" rel="icon">
    <link href="{%static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Cardo:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{%static 'assets/vendor/bootstrap/css/bootstrap.min.css'%} " rel="stylesheet" />
    <link href="{%static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%} " rel="stylesheet" />
    <link href="{%static 'assets/vendor/swiper/swiper-bundle.min.css'%} " rel="stylesheet" />
    <link href="{%static 'assets/vendor/glightbox/css/glightbox.min.css'%} " rel="stylesheet" />
    <link href="{%static 'assets/vendor/aos/aos.css'%}" rel="stylesheet" />
    <link href="{%static 'assets/css/main.css'%} " rel="stylesheet" />
    
    <title>
        {% block title %}
        멍멍냥냥
        {% endblock title %}
    </title>
</head>

<body>
    {% include 'navbar.html' %}
    {% block main_area %}
    
    {% endblock main_area %}
    {% include 'footer.html' %}
</body>

</html>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<!-- Vendor JS Files -->
<script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{%static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
<script src="{%static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
<script src="{%static 'assets/vendor/aos/aos.js'%}"></script>
<script src="{%static 'assets/vendor/php-email-form/validate.js'%}"></script>

<!-- Template Main JS File -->
<script src="{%static 'assets/js/main.js'%}"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="{%static 'assets/js/masonry.min.js'%}"></script>

templates/pet_templates/boards.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<br>
<br>
<br>
<br>
<br>
<nav id="bo_cate">
    <h2>자유게시판 카테고리</h2>
    <ul>
        <li><a href="#" id="bo_cate_on">전체</a></li>
        <li><a href="#">자유</a></li>
        <li><a href="#">기타</a></li>
        <li><a href="#">노한진</a></li>
    </ul>
</nav>

<form method="post">
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container single-col-max-width">
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div id="img-col" class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">어떻게 해야 한진이가 만족할 수 있을까?</a></h3>
                        <div class="meta mb-1"><span class="date">Published 2 days ago</span><span class="time">5 min read</span><span class="comment"><a class="text-link" href="#">8 comments</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->         
        </div>
        <div class="container single-col-max-width">
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div id="img-col" class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">과연 그런 날이 올까?</a></h3>
                        <div class="meta mb-1"><span class="date">Published 2 days ago</span><span class="time">5 min read</span><span class="comment"><a class="text-link" href="#">8 comments</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->     
        </div>    
            <div class="container single-col-max-width">
                <div class="item mb-5">
                    <div class="row g-3 g-xl-0">
                        <div id="img-col" class="col-2 col-xl-3">
                            <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image">
                        </div>
                        <div class="col">
                            <h3 class="title mb-1"><a class="text-link" href="blog-post.html">내 생각에 그런 날은 오지 않는다.</a></h3>
                            <div class="meta mb-1"><span class="date">Published 2 days ago</span><span class="time">5 min read</span><span class="comment"><a class="text-link" href="#">8 comments</a></span></div>
                            <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                            <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                        </div><!--//col-->
                    </div><!--//row-->
                </div><!--//item-->         
            </div>
        </div>
    </section>
    <!-- 페이지 -->
    <div>
        <nav class="pg_wrap"
            style="text-align: center; position: relative; top: 50%; left: 45%; margin: -150px Opx Opx -200px;">
            <strong class="pg_current">1</strong>
            <a href="#page=2" class="pg_page">2</a>
            <a href="#page=3" class="pg_page">3</a>
            <a href="#page=11" class="pg_page">></a>
            <a href="#page=13" class="pg_page">>></a>
        </nav>
        <ul><a href="{% url 'pet:create_post' %}" class="btn_b01 btn float-end"><i class="bi bi-pencil-square"></i>글쓰기</a>
        </ul>
    </div>
    <!-- 페이지 -->
</form>
<br>
{% endblock main_area %}

templates/pet_templates/footer.html
{% load static %}
<footer id="footer" class="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>멍멍냥냥</span></strong> All Rights Reserved
        </div>
        <div class="credits">
            <a href="#">Designed by 멍멍냥냥</a>
        </div>
        <div class="header-social-links">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
        </div>
    </div>
</footer>

templates/pet_templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}

<body class="box">
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="hero d-flex flex-column justify-content-center align-items-center" data-aos="fade"
    data-aos-delay="1500" style="opacity: 0.9; color: #FFDCA9; background-color: white;">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 text-center">
          <!-- <h2>여기는<span style="background-color: #F9B5D0;">동물농장</span>입니다</h2> -->
          <br>
          <h2 style="color: dimgray; text-shadow: 2px 2px 2px #FCF9BE;">이곳은 <span><img
                src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img>멍멍냥냥<img
                src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img></span> 입니다</h2>
          <p style="color: dimgrey; text-shadow: 2px 2px 2px #FCF9BE;">멍멍 냥냥 으르르르 야옹 깨갱</p>
          <a href="contact.html" class="btn-get-started"
            style="background-color: #FAAB78; text-shadow: 2px 2px 2px gray;">둘러보기&nbsp;<img
              src="{% static 'assets\img\paw.png' %}" style="width: 15px; height: 15px;"></img></a>
        </div>
      </div>
    </div>
  </section>
  <!-- End Hero Section -->

  <!-- 카드형식 그리드 템플릿 -->
  <main id="content" class="content" role="main">
    <div class="wraps">
      <img src="" class="wrapshadow">
      <!-- 그리드 카드 -->
      <div class="grid">
        <div class="grid-item">
          <article class="post">
            <a href="article.html"><img src="{% static 'assets/img/paw.png' %}" style="width: 365px; height:225px;"></a>
            <div class="wrapgriditem">
              <header class="post-header">
                <h2 class="post-title"><a href="article.html">메인 화면 테스트</a></h2>
              </header>
              <section class="post-excerpt">
                <p>
                  메인 화면 카드 섹션 내용 테스트 <a class="read-more" href="/retro-is-the-new-modern/">&raquo;</a>
                </p>
              </section>
              <footer class="post-meta">
                <img class="author-thumb" src="{% static 'assets/img/cat.png' %}" alt="David" nopin="nopin" />
                <a href="author.html">이현복</a>
                <time class="post-date" datetime="2022-12-21">21 December 2022</time>
              </footer>
            </div>
          </article>
        </div>
        <!-- 그리드 카드 -->

        <!-- 그리드 카드 -->
        <div class="grid-item">
          <article class="post tag-romance">
            <a href="article.html"><img src="{% static 'assets/img/gallery/1111.jpg' %}"
                style="width: 365px; height:225px;"></a>
            <div class="wrapgriditem">
              <header class="post-header">
                <h2 class="post-title"><a href="article.html">메인 화면 테스트</a></h2>
              </header>
              <section class="post-excerpt">
                <p>
                  메인 화면 카드 섹션 내용 테스트 <a class="read-more" href="/retro-is-the-new-modern/">&raquo;</a>
                </p>
              </section>
              <footer class="post-meta">
                <img class="author-thumb" src="{% static 'assets/img/dog.png' %}" alt="David" nopin="nopin" />
                <a href="author.html">이현복</a>
                <time class="post-date" datetime="2022-12-21">21 December 2022</time>
              </footer>
            </div>
          </article>
        </div>
        <!-- 그리드 카드 -->

        <!-- 그리드 카드 -->
        <div class="grid-item">
          <article class="post">
            <a href="article.html"><img src="{% static 'assets/img/gallery/1111.jpg' %}"
                style="width: 365px; height:225px;"></a>
            <div class="wrapgriditem">
              <header class="post-header">
                <h2 class="post-title"><a href="article.html">메인 화면 테스트</a></h2>
              </header>
              <section class="post-excerpt">
                <p>
                  메인 화면 카드 섹션 내용 테스트 <a class="read-more" href="/retro-is-the-new-modern/">&raquo;</a>
                </p>
              </section>
              <footer class="post-meta">
                <img class="author-thumb" src="{% static 'assets/img/chick.png' %}" alt="David" nopin="nopin" />
                <a href="author.html">이현복</a>
                <time class="post-date" datetime="2022-12-21">21 December 2022</time>
              </footer>
            </div>
          </article>
        </div>
        <!-- 그리드 카드 -->
      </div>
    </div>
  </main>
  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>
  {% endblock main_area%}

templates/pet_templates/hotel_detail.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<br>
<br>
<br>
<br>
<br>
<nav>
    <ul>
    </ul>
</nav>

<form method="post">
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container single-col-max-width">
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                        <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" style="width:1000px; height:500px;" alt="image">

                    <div class="col" style="margin-right: 30px;">
                        <h3 class="title mb-1"><a class="text-link" href="/호텔링크">멍멍호텔</a></h3>
                        <div class="intro" style="color: black;">
                            <table>
                                    <tr>
                                        <th>호텔위치 : 경기도</th>
                                    </tr>
                                    <tr>
                                        <th>특징 : 음식이 친절하고 사장님이 맛있어요</th>
                                    </tr>
                                    <tr>
                                        <th>평점 : 별이 다섯개</th>
                                    </tr>
                                    <tr>
                                            <th>이용후기 : 한꾺인뜰 꼮뽀쎼요 이 호톌 찐짜 떠려워요</th>                                            
                                    </tr>
                            </table>
                        </div>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->         
        </div>
    </section>
</form>
<br>
{% endblock main_area %}

templates/pet_templates/post_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main_area %}
<br>
<br>
<br>
<br>
<br>
<section class="container" style="color: #FAAB78;">
    <h1>Create New Post</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            <!--  form | crispy  crispy 지우니까 되네; -->
            {{ form | crispy }} 
        </table>
        <div id="div_id_tags_str">
            <label for="id_tags_str">Tags </label>
            <input type="text" name="tags_str" id="id_tags_str" class="textInput form-control" >
        </div>
        <button type="submit" class="btn float-end" style="text-align: center; color: white; text-shadow: 2px 2px 2px gray; background-color: #FAAB78;">Submit</button>
    </form>
</section>
{% endblock main_area %}