django_mini_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, home_view
from .views import UserCreateView, UserCreateDoneTV, NaverMap, NaverMapCenter
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', HomeView.as_view(), name="home"),
    path('', home_view, name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    #계정 생성 완료됐다는 메세지 보여줌
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('naver_map/hospital', NaverMap.as_view(), name="naver_map"),
    path('naver_map/center', NaverMapCenter.as_view(), name="naver_map_center"),
    path('summernote/', include('django_summernote.urls')),
    path('Account/', include('Account.urls')),
    path('pet/', include('pet.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name="pet"
urlpatterns = [
    path('create_post/',views.PetPostCreate.as_view(), name="create_post"),
    path('board/', views.BoardView.as_view(), name="board"),
    path('board/<int:pk>/', views.PetPostDetail.as_view(), name='post_deatil'),
    path('board/update_post/<int:pk>/',views.PetPostUpdate.as_view(), name = 'post_update'),
    path('board/<str:slug>/', views.pet_post_category_page), 
    
    path('animal/', views.AnimalView.as_view(), name="animal"),
    path('animal_detail/<int:pk>/', views.AnimalDetailView.as_view(), name="animal_detail"),
    path('hotel/', views.HotelView.as_view(), name="hotel"),
    path('hotel_detail/<int:pk>/', views.HotelDetailView.as_view(), name="hotel_detail"),
    path('hotel/category/<str:slug>/', views.hotel_category_page),
    path('mybaby/', views.ShowOffPostList.as_view(), name="mybaby"),
    path('mybaby/create_post/',views.ShowoffPostCreate.as_view(), name="mybaby_create_post"),
    path('mybaby/<int:pk>/', views.ShowoffPostDetail.as_view(), name="mybaby_detail"),
    path('mybaby/update_post/<int:pk>/',views.ShowOffPostUpdate.as_view(), name = 'mybaby_update'),
    path('mybaby/<str:slug>/', views.show_off_post_category_page), 
    
    path('recommend/', views.RecommendList.as_view(), name="recommend"),
    path('recommend/create_post/',views.RecommendPostCreate.as_view(), name="recommend_create_post"),
    path('recommend/<int:pk>/', views.RecommendPostDetail.as_view(), name="recommend_detail"),
    path('recommend/update_post/<int:pk>/',views.RecommendPostUpdate.as_view(), name = 'recommend_update'),
    path('recommend/<str:slug>/', views.recommend_post_category_page), 
    
    path('news/', views.NewsList.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetail.as_view(), name="news_detail"),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import PetPost, RecommendPost, ShowoffPost

class PostForm(forms.ModelForm):
    class Meta:
        model = PetPost
        fields = ['title', 'thumnail', 'content', 'category']
        widgets = {
            'content' : SummernoteWidget(
                #attrs에 summernote에 대한 설정값들을 key/value 형식을 주면 된다.
                attrs={
                    'summernote': {
                    'width': '100%', 
                    'height': '400px',
                    'iframe': False,
                    'lang': 'ko-KR',
                    'codemirror': {
                        'mode': 'htmlmixed',
                    },
                }}
            ),
        }
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "200글자 넘어가면 에러납니다"
        
#추천 폼
class RecommendPostForm(forms.ModelForm):
    class Meta:
        model = RecommendPost
        fields = ['title', 'thumnail', 'content', 'category']
        widgets = {
            'content' : SummernoteWidget(
                #attrs에 summernote에 대한 설정값들을 key/value 형식을 주면 된다.
                attrs={
                    'summernote': {
                    'width': '100%', 
                    'height': '400px',
                    'iframe': False,
                    'lang': 'ko-KR',
                    'codemirror': {
                        'mode': 'htmlmixed',
                    },
                }}
            ),
        }
    def __init__(self, *args, **kwargs):
        super(RecommendPostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "200글자 넘어가면 에러납니다"


#내새끼 자랑 폼
class ShowoffPostForm(forms.ModelForm):
    class Meta:
        model = ShowoffPost
        fields = ['title','thumnail','content', 'category']
        widgets = {
            'content' : SummernoteWidget(
                #attrs에 summernote에 대한 설정값들을 key/value 형식을 주면 된다.
                attrs={
                    'summernote': {
                    'width': '100%', 
                    'height': '400px',
                    'iframe': False,
                    'lang': 'ko-KR',
                    'codemirror': {
                        'mode': 'htmlmixed',
                    },
                }}
            ),
        }
    def __init__(self, *args, **kwargs):
        super(ShowoffPostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "200글자 넘어가면 에러납니다"

pet/views.py
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import PetPost, AnimalCategory, NewsScrap, SaveAnimalCategory, Animals, HotelCategory, KoreaHotel, SGIHotel, PostCategory
from .models import RecommendPost, ShowoffPost
from django.core.exceptions import PermissionDenied
from .forms import PostForm, RecommendPostForm, ShowoffPostForm

class BoardView(ListView):
    template_name = "pet/boards.html"
    model = PetPost
    ordering = '-pk' #postlist 데이터 랜더링 시 pk 순서대로 내림차순으로 랜더링된다.
    paginate_by = 10 #pagination을 할 때 한 페이지당 몇개의 데이터를 보이게 할 지 설정한다.
    def get_context_data(self, **kwargs):
        #다른 객체(데이터)들도 context에 넣어 보내고 싶다면 get_context_data 메서드를 구현하는 것으로 해결할 수 있다.
        #get_context_data는 dict 형식으로 반환되기 때문에 일반적인 context에는 PostList의 모든 데이터가 담겨져 있고
        #그 뒤에 key값과 value로 원하는 형식의 데이터를 넣으면 된다.
        context = super(BoardView,self).get_context_data()
        context['categories'] = AnimalCategory.objects.all()
        context['no_category_post_count'] = PetPost.objects.filter(category=None).count()
        return context
        
    
    
class PetPostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = PetPost
    form_class = PostForm
    template_name = 'pet/pet_tip_post.html'
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff or self.request.user.is_authenticated

    def form_valid(self,form):
        current_user = self.request.user #사용자 정보 가져옴
        if current_user.is_authenticated or (current_user.is_staff or current_user.is_superuser): #인증된 사용자인지 체크
            form.instance.author = current_user #form 즉 post 제작 form의 소유자를 해당 사용자로 지정한다
            form.instance.post_category = PostCategory.objects.get(name='pet_post')
            #print(f"category - {form.data.get('category')}")
            if form.data.get('category') is "":
                form.instance.category = AnimalCategory.objects.get(name = "etc")
            #여기서 response는 변수이다. 입력한 form의 입력값들이 다 검증되었는지 저장한다
            response =  super(PetPostCreate, self).form_valid(form) #PostCreate를 이용해 form에 들어온 내용들이 모두 해당 데이터필드에 맞게 지정되면 저장한다.
            return response #DB에 저장
        
        else:
            return redirect('pet/board') #아니면 blog 페이지로 이동

class PetPostDetail(DetailView):
    #CBV 방식 view 작성에서 DetailView 상속 받기 때문에 template 파일 이름을 post_detail.html로 하면, template_name 변수는 생략해도 됨
    #규칙이기 때문에 규칙에 어긋하면 적용이 되지 않음.
    model = PetPost
    template_name = 'pet/board_detail.html'
    def get_context_data(self, **kwargs):
        context = super(PetPostDetail,self).get_context_data()
        context['categories'] = AnimalCategory.objects.all()
        context['no_category_post_count'] = PetPost.objects.filter(category=None).count()
        return context
    
    
class PetPostUpdate(LoginRequiredMixin, UpdateView):
    model = PetPost
    form_class = PostForm
    # fields = ['title','hook_text','content','head_image','file_upload','category','tags']
    template_name = 'pet/post_update_form.html'
    #얘는 접속이 get인지 post인지 확인. get이면 포스트 update form 보여주고 post이면 form의 저장된 내용을 검증하고 통과되면 DB에 저장하는 역할
    #여기서는 만약 권한이 없으면 GET이든 POST이든 둘다 막아버림
    def dispatch(self, request, *args, **kwargs):
        #현재 접속한 user가 인증되었고 user가 해당 게시글의 소유자이면
        if request.user.is_authenticated and request.user == self.get_object().author: 
            return super(PetPostUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self,form):
        current_user = self.request.user #사용자 정보 가져옴
        if current_user.is_authenticated or (current_user.is_staff or current_user.is_superuser): #인증된 사용자인지 체크
            form.instance.author = current_user #form 즉 post 제작 form의 소유자를 해당 사용자로 지정한다
            #여기서 response는 변수이다. 입력한 form의 입력값들이 다 검증되었는지 저장한다
            form.instance.post_category = PostCategory.objects.get(name='pet_post')
            #print(f"category - {form.data.get('category')}")
            if form.data.get('category') is "":
                form.instance.category = AnimalCategory.objects.get(name = "etc")
            response =  super(PetPostUpdate, self).form_valid(form) #PostCreate를 이용해 form에 들어온 내용들이 모두 해당 데이터필드에 맞게 지정되면 저장한다.
            return response #DB에 저장
        
        else:
            return redirect('pet/') #아니면 blog 페이지로 이동
        
    
#category끼리만 모아서 따로 페이지를 만들어주는 기능.
def pet_post_category_page(request, slug):
    print(slug)
    if slug == 'no_category':
        category = "미분류"
        post_list = PetPost.objects.filter(category=None)
    else:
        category = AnimalCategory.objects.get(slug=slug)
        post_list = PetPost.objects.filter(category=category).order_by("-created_at")
    
    return render(request, 'pet/boards.html',
                {
                    'slug' : slug,
                    'petpost_list': post_list, #해당 카테고리 정보들만 저장
                    'categories' : AnimalCategory.objects.all(), #전체 데이터 저장
                    #카테고리 없을 시 갯수 가져옴
                    'no_category_post_count' : PetPost.objects.filter(category=None).count(), #카테고리 없으면 갯수 지정
                    'category' : category #지정된 카테고리
                }
            )
    
class NewsList(ListView):
    model = NewsScrap
    template_name = 'pet/news_list.html'
    paginate_by = 10 # 페이지네이션 기능 활성화

class NewsDetail(DetailView):
    model = NewsScrap
    template_name = "pet/news_detail.html"

class AnimalView(ListView):
    model = Animals
    template_name = "pet/animal.html"
    paginate_by = 10
    ordering = '-pk'

class AnimalDetailView(DetailView):
    model = Animals
    template_name = "pet/animal_detail.html"
    context_object_name = 'animals'
    def get_context_data(self, **kwargs):
        context = super(AnimalDetailView,self).get_context_data()
        context['categories'] = SaveAnimalCategory.objects.all()
        return context

class HotelView(ListView):
    template_name = "pet/hotel.html"
    model = KoreaHotel
    paginate_by = 10
    ordering = '-kh_hotel_score'
    def get_context_data(self, **kwargs):
        #다른 객체(데이터)들도 context에 넣어 보내고 싶다면 get_context_data 메서드를 구현하는 것으로 해결할 수 있다.
        #get_context_data는 dict 형식으로 반환되기 때문에 일반적인 context에는 PostList의 모든 데이터가 담겨져 있고
        #그 뒤에 key값과 value로 원하는 형식의 데이터를 넣으면 된다.
        context = super(HotelView,self).get_context_data()
        context['categories'] = HotelCategory.objects.all()
        return context
    
def hotel_category_page(request, slug):
    print(slug)
    if slug == "전국":
        category = HotelCategory.objects.get(slug=slug)
        post_list = KoreaHotel.objects.all().order_by("-kh_hotel_score")
        all_post = "전국"
    elif slug == 'no_category':
        category = "미분류"
        post_list = SGIHotel.objects.filter(category=None)
        all_post = "전국아님"
    else:
        category = HotelCategory.objects.get(slug=slug)
        post_list = SGIHotel.objects.filter(category=category).order_by("-sgi_hotel_score")
        all_post = "전국아님"
    print(post_list)
    return render(request, 'pet/hotel_sgi.html',
                {
                    'slug' : slug,
                    'hotel_list': post_list, #해당 카테고리 정보들만 저장
                    'categories' : HotelCategory.objects.all(), #전체 데이터 저장
                    #카테고리 없을 시 갯수 가져옴
                    'no_category_post_count' : KoreaHotel.objects.filter(category=None).count(), #카테고리 없으면 갯수 지정
                    'category' : category, #지정된 카테고리
                    'all_post' : all_post
                }
            )
    

class HotelDetailView(DetailView):
    model = KoreaHotel
    template_name = "pet/hotel_detail.html"
    def get_context_data(self, **kwargs):
        context = super(HotelDetailView, self).get_context_data()
        context['categories'] = HotelCategory.objects.all()
        return context

class NewsView(TemplateView):
    template_name = "pet/news.html"


class RecommendPostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = RecommendPost
    form_class = RecommendPostForm
    template_name = 'pet/pet_tip_post.html'
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff or self.request.user.is_authenticated

    def form_valid(self,form):
        current_user = self.request.user #사용자 정보 가져옴
        if current_user.is_authenticated or (current_user.is_staff or current_user.is_superuser): #인증된 사용자인지 체크
            form.instance.author = current_user #form 즉 post 제작 form의 소유자를 해당 사용자로 지정한다
            form.instance.post_category = PostCategory.objects.get(name='recommend_post')
            if form.data.get('category') is "":
                form.instance.category = AnimalCategory.objects.get(name = "etc")
            #여기서 response는 변수이다. 입력한 form의 입력값들이 다 검증되었는지 저장한다
            response =  super(RecommendPostCreate, self).form_valid(form) #PostCreate를 이용해 form에 들어온 내용들이 모두 해당 데이터필드에 맞게 지정되면 저장한다.
            return response #DB에 저장
        
        else:
            return redirect('pet/recommend') #아니면 blog 페이지로 이동

class RecommendList(ListView):
    template_name = "pet/recommend.html"
    model = RecommendPost
    paginate_by = 10
    ordering = '-pk'
    def get_context_data(self, **kwargs):
        #다른 객체(데이터)들도 context에 넣어 보내고 싶다면 get_context_data 메서드를 구현하는 것으로 해결할 수 있다.
        #get_context_data는 dict 형식으로 반환되기 때문에 일반적인 context에는 PostList의 모든 데이터가 담겨져 있고
        #그 뒤에 key값과 value로 원하는 형식의 데이터를 넣으면 된다.
        context = super(RecommendList,self).get_context_data()
        context['categories'] = AnimalCategory.objects.all()
        context['no_category_post_count'] = RecommendPost.objects.filter(category=None).count()
        return context

class RecommendPostDetail(DetailView):
    #CBV 방식 view 작성에서 DetailView 상속 받기 때문에 template 파일 이름을 post_detail.html로 하면, template_name 변수는 생략해도 됨

pet/templates/pet/pet_tip_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Pet 정보 공유 게시판 작성
{% endblock title %}
{%block main_area%}
<section class="container">
    <h1>Create New Post</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            <!-- 얘는 crispy form 전체 적용 -->
            {{ form | crispy }}
        </table>
        <div style="text-align: center;"><button type="submit" class="btn" style="font-weight: bold; width: 200px; text-align: center; color: white; text-shadow: 2px 2px 2px gray; background-color: #FAAB78;">Submit</button></div>
    </form>
</section>
{%endblock main_area%}

pet/templates/pet/recommend.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<script src="http://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    window.onload = function(){
        var category = document.querySelectorAll(".cate_item");
        //console.log(category)
        var all_check = true
        for(var i=0; i<category.length; i++){
            //console.log(category[i].innerHTML);
            //console.log("{{slug}}")
            if(category[i].innerHTML == "{{slug}}"){
                category[i].style.color='white'
                category[i].style.background = '#FAAB78'
                all_check = false
            }
            console.log(all_check)
        }
        if(all_check){
            category[0].style.color="white"
            category[0].style.background = '#FAAB78'
        }
    }
</script>
<section class="blog-list px-3 py-5 p-md-5">
    <nav id="bo_cate">
    <ul>
        <li>
            <a href="{%url 'pet:recommend'%}" class = "cate_item">All</a>
        </li>
        {%for category in categories%}
        <li>
            <a href="{{category.get_absolute_url_recommend}}" class = "cate_item">{{category}}</a>
        </li>
        {%endfor%}
        {%if user.is_authenticated or user.is_superuser or user.is_staff %}
        <li class="float-end"><a href="{%url 'pet:recommend_create_post'%}" class="btn float-right" title="글쓰기">
            <i class="bi bi-pencil-square"></i>글쓰기</a>
        </li>
        {%endif%}
    </ul>
</nav>
<form method="post">
        {% if recommendpost_list.exists %}
            {% for p in recommendpost_list %}
                <div class="container single-col-max-width" id = "petpost-{{p.pk}}">
                    <div class="item mb-5">
                        <div class="row g-3 g-xl-0">
                            {% if p.thumnail %}
                            <div id="img-col" class="col-2 col-xl-3">
                                <img class="card-img-top" src="{{ p.thumnail.url }}" alt="{{ p }} head image" style="width: 200px; height:120px"/>
                            </div>
                            {% else %}
                            <div id="img-col" class="col-2 col-xl-3">
                                <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 200px; height:120px">
                            </div>
                            {%endif%}
                            <div class="col">
                                <h3 class="title mb-1"><a class="text-link" href="{{p.get_absolute_url}}">{{p.title}}</a></h3>
                                <div class="meta mb-1"><span class="date">{{p.created_at}}</div>
                                <span class="card-body text-dark">{{p.content | striptags |  truncatewords:30}}</span>
                                <div><a class="intro" role="button">{{p.category}}</a></div>
                                <a class="text-link" href="{{p.get_absolute_url}}">Read more &rarr;</a>
                            </div><!--//col-->
                        </div><!--//row-->
                    </div><!--//item-->         
                </div>
            {%endfor%}
        {% else %}
        <h3>아직 게시물이 없습니다.</p>
        {% endif %}
        {% if is_paginated %}

        <!-- 페이지 -->
        <div>
            <nav class="pg_wrap" style="text-align: center; position: relative; top: 50%; left: 45%; margin: -150px Opx Opx -200px;" aria-label="Pagination">
                <hr class="my-0" />
                <ul class="pagination justify-content-center my-4">
                    <!-- 이전 페이지로 돌아가기 has_previous로 이전이 있는지 확인-->
                    {% if page_obj.has_previous %}
                    <!-- 이전 페이지 객체가 있으면 [prev]버튼 활성화 -->
                    <li class="page-item">
                        <a class="page-link"
                            href="{% url 'pet:board' %}?page={{ page_obj.previous_page_number }}"
                            tabindex="-1">Prev</a>
                    </li>
                    {% else %}
                    <!-- 이전페이지 객체가 없으면 [prev]버튼 비활성화. #는 무의미한 url을 의미한다. -->
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Prev</a>
                    </li>
                    {% endif %}
                    <!-- 페이지를 번호로 출력하기. 전체 페이지 번호를 출력(적용)하며 현재 선택된 페이지는 비활성화, 다른 페이지들은 활성화시킴. -->
                    {% for page in page_obj.paginator.page_range %}
                    <!-- 현재 선택한 페이지 번호는 비활성화 시킴 -->
                    {% if page_obj.number == forloop.counter %}
                    <!-- 만약 현재 선택된  -->
                    <li class="page-item disabled" aria-current="page">
                        <a class="page-link" style="background-color: #7eacf6;"
                            href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <!-- 현재 선택한 페이지 번호는 활성화 시킴 -->
                    <li class="page-item" aria-current="page">
                        <!-- request.path는 현재 페이지의 url을 가져오는 의미이다.-->
                        <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter}}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    <!-- 다음 페이지로 가기 -->
                    {% if page_obj.has_next %}
                    <!-- 이전페이지 객체가 있으면 [Next]버튼 활성화 -->
                    <li class="page-item">
                        <a class="page-link"
                            href="{% url 'pet:board' %}?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {%endif%}

    <!-- 페이지 -->
</form>
</section>
{% endblock main_area %}

pet/templates/pet/show_off.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<script src="http://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    window.onload = function(){
        var category = document.querySelectorAll(".cate_item");
        //console.log(category)
        var all_check = true
        for(var i=0; i<category.length; i++){
            //console.log(category[i].innerHTML);
            //console.log("{{slug}}")
            if(category[i].innerHTML == "{{slug}}"){
                category[i].style.color='white'
                category[i].style.background = '#FAAB78'
                all_check = false
            }
            console.log(all_check)
        }
        if(all_check){
            category[0].style.color="white"
            category[0].style.background = '#FAAB78'
        }
    }
</script>
<section class="blog-list px-3 py-5 p-md-5">
    <nav id="bo_cate">
    <ul>
        <li>
            <a href="{%url 'pet:mybaby'%}" class = "cate_item">All</a>
        </li>
        {%for category in categories%}
        <li>
            <a href="{{category.get_absolute_url_show_off}}" class = "cate_item">{{category}}</a>
        </li>
        {%endfor%}
        {%if user.is_authenticated or user.is_superuser or user.is_staff %}
        <li class="float-end"><a href="{%url 'pet:mybaby_create_post'%}" class="btn float-right" title="글쓰기">
            <i class="bi bi-pencil-square"></i>글쓰기</a>
        </li>
        {%endif%}
    </ul>
</nav>
<form method="post">
        {% if showoffpost_list.exists %}
            {% for p in showoffpost_list %}
                <div class="container single-col-max-width" id = "petpost-{{p.pk}}">
                    <div class="item mb-5">
                        <div class="row g-3 g-xl-0">
                            {% if p.thumnail %}
                            <div id="img-col" class="col-2 col-xl-3">
                                <img class="card-img-top" src="{{ p.thumnail.url }}" alt="{{ p }} head image" style="width: 200px; height:120px"/>
                            </div>
                            {% else %}
                            <div id="img-col" class="col-2 col-xl-3">
                                <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 200px; height:120px">
                            </div>
                            {%endif%}
                            <div class="col">
                                <h3 class="title mb-1"><a class="text-link" href="{{p.get_absolute_url}}">{{p.title}}</a></h3>
                                <div class="meta mb-1"><span class="date">{{p.created_at}}</div>
                                <span class="card-body text-dark">{{p.content | striptags |  truncatewords:30}}</span>
                                <div><a class="intro" role="button">{{p.category}}</a></div>
                                <a class="text-link" href="{{p.get_absolute_url}}">Read more &rarr;</a>
                            </div><!--//col-->
                        </div><!--//row-->
                    </div><!--//item-->         
                </div>
            {%endfor%}
        {% else %}
        <h3>아직 게시물이 없습니다.</p>
        {% endif %}
        {% if is_paginated %}

        <!-- 페이지 -->
        <div>
            <nav class="pg_wrap" style="text-align: center; position: relative; top: 50%; left: 45%; margin: -150px Opx Opx -200px;" aria-label="Pagination">
                <hr class="my-0" />
                <ul class="pagination justify-content-center my-4">
                    <!-- 이전 페이지로 돌아가기 has_previous로 이전이 있는지 확인-->
                    {% if page_obj.has_previous %}
                    <!-- 이전 페이지 객체가 있으면 [prev]버튼 활성화 -->
                    <li class="page-item">
                        <a class="page-link"
                            href="{% url 'pet:board' %}?page={{ page_obj.previous_page_number }}"
                            tabindex="-1">Prev</a>
                    </li>
                    {% else %}
                    <!-- 이전페이지 객체가 없으면 [prev]버튼 비활성화. #는 무의미한 url을 의미한다. -->
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Prev</a>
                    </li>
                    {% endif %}
                    <!-- 페이지를 번호로 출력하기. 전체 페이지 번호를 출력(적용)하며 현재 선택된 페이지는 비활성화, 다른 페이지들은 활성화시킴. -->
                    {% for page in page_obj.paginator.page_range %}
                    <!-- 현재 선택한 페이지 번호는 비활성화 시킴 -->
                    {% if page_obj.number == forloop.counter %}
                    <!-- 만약 현재 선택된  -->
                    <li class="page-item disabled" aria-current="page">
                        <a class="page-link" style="background-color: #7eacf6;"
                            href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <!-- 현재 선택한 페이지 번호는 활성화 시킴 -->
                    <li class="page-item" aria-current="page">
                        <!-- request.path는 현재 페이지의 url을 가져오는 의미이다.-->
                        <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter}}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    <!-- 다음 페이지로 가기 -->
                    {% if page_obj.has_next %}
                    <!-- 이전페이지 객체가 있으면 [Next]버튼 활성화 -->
                    <li class="page-item">
                        <a class="page-link"
                            href="{% url 'pet:board' %}?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {%endif%}

    <!-- 페이지 -->
</form>
<br>
</section>
{% endblock main_area %}