Account/urls.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import path
from .views import UserView, profile_delete_view, userDelete, get_user_write_post

# Create your views here.
app_name="Account"
urlpatterns = [
    # path('account/view',UserView.as_view(), name = "account_view" ),
    path('account/view',get_user_write_post, name = "account_view" ),
    path('delete_success/', userDelete, name="delete_success"),
]

django_mini_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, home_view
from .views import UserCreateView, UserCreateDoneTV, NaverMap, NaverMapCenter
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', HomeView.as_view(), name="home"),
    path('', home_view, name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    #계정 생성 완료됐다는 메세지 보여줌
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('naver_map/hospital', NaverMap.as_view(), name="naver_map"),
    path('naver_map/center', NaverMapCenter.as_view(), name="naver_map_center"),
    path('summernote/', include('django_summernote.urls')),
    path('Account/', include('Account.urls')),
    path('pet/', include('pet.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name="pet"
urlpatterns = [
    path('create_post/',views.PetPostCreate.as_view(), name="create_post"),
    path('board/', views.BoardView.as_view(), name="board"),
    path('board/<int:pk>/', views.PetPostDetail.as_view(), name='post_deatil'),
    path('board/update_post/<int:pk>/',views.PetPostUpdate.as_view(), name = 'post_update'),
    path('board/<str:slug>/', views.pet_post_category_page), 
    
    path('animal/', views.AnimalView.as_view(), name="animal"),
    path('animal_detail/<int:pk>/', views.AnimalDetailView.as_view(), name="animal_detail"),
    path('hotel/', views.HotelView.as_view(), name="hotel"),
    path('hotel_detail/<int:pk>/', views.HotelDetailView.as_view(), name="hotel_detail"),
    path('hotel/category/<str:slug>/', views.hotel_category_page),
    path('mybaby/', views.ShowOffPostList.as_view(), name="mybaby"),
    path('mybaby/create_post/',views.ShowoffPostCreate.as_view(), name="mybaby_create_post"),
    path('mybaby/<int:pk>/', views.ShowoffPostDetail.as_view(), name="mybaby_detail"),
    path('mybaby/update_post/<int:pk>/',views.ShowOffPostUpdate.as_view(), name = 'mybaby_update'),
    path('mybaby/<str:slug>/', views.show_off_post_category_page), 
    
    path('recommend/', views.RecommendList.as_view(), name="recommend"),
    path('recommend/create_post/',views.RecommendPostCreate.as_view(), name="recommend_create_post"),
    path('recommend/<int:pk>/', views.RecommendPostDetail.as_view(), name="recommend_detail"),
    path('recommend/update_post/<int:pk>/',views.RecommendPostUpdate.as_view(), name = 'recommend_update'),
    path('recommend/<str:slug>/', views.recommend_post_category_page), 
    
    path('news/', views.NewsList.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetail.as_view(), name="news_detail"),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {%block title%}
            멍멍냥냥
            {%endblock title%}
        </title>
        <!-- Favicon-->
        <link href="{%static 'assets/img/favicon.png'%}" rel="icon">
        <link href="{%static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">
        
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Cardo:ital,wght@0,400;0,700;1,400&display=swap"
            rel="stylesheet">

        <!-- Core theme CSS (includes Bootstrap)-->

        <!-- Vendor CSS Files -->
        <link href="{%static 'assets/vendor/bootstrap/css/bootstrap.min.css'%} " rel="stylesheet" />
        <link href="{%static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%} " rel="stylesheet" />
        <link href="{%static 'assets/vendor/swiper/swiper-bundle.min.css'%} " rel="stylesheet" />
        <link href="{%static 'assets/vendor/glightbox/css/glightbox.min.css'%} " rel="stylesheet" />
        <link href="{%static 'assets/vendor/aos/aos.css'%}" rel="stylesheet" />
        <link href="{%static 'assets/css/main.css'%} " rel="stylesheet" />

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=4eag4iopmh"></script>
    </head>
    <body id="page-top">
        {%include 'navbar.html'%}
        <body id="page-top" style="height: 100%; display: flex; flex-direction: column; margin: 0;">
            <section style="flex: 1; margin-top: 60px;">
            {% block main_area %}
            {% endblock main_area%}
            </section>
        </body>
        {%include 'footer.html'%}
    </body>
</html>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<!-- Vendor JS Files -->
<script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="{%static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
<script src="{%static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
<script src="{%static 'assets/vendor/aos/aos.js'%}"></script>
<script src="{%static 'assets/vendor/php-email-form/validate.js'%}"></script>
<!-- Core theme JS-->

<script src="{%static 'js/scripts.js'%}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

<!-- Template Main JS File -->
<script src="{%static 'assets/js/main.js'%}"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="{%static 'assets/js/masonry.min.js'%}"></script>

templates/footer.html
{% load static %}
<footer id="footer" class="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>멍멍냥냥</span></strong> All Rights Reserved
        </div>
        <div class="credits">
            <a href="#">Designed by 멍멍냥냥</a>
        </div>
        <div class="header-social-links">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
        </div>
    </div>
</footer>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block main_area %}

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="hero d-flex flex-column justify-content-center align-items-center" data-aos="fade"
    data-aos-delay="1500" style="opacity: 0.9; color: #FFDCA9; background-color: white; margin-top: 50px;">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 text-center">
          <!-- <h2>여기는<span style="background-color: #F9B5D0;">동물농장</span>입니다</h2> -->
          <br>
          <h2 style="color: dimgray; text-shadow: 2px 2px 2px #FCF9BE;">이곳은 <span><img
                src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img>멍멍냥냥<img
                src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img></span> 입니다</h2>
          <p style="color: dimgrey; text-shadow: 2px 2px 2px #FCF9BE;">멍멍 냥냥 으르르르 야옹 깨갱</p>
          <a href="{% url 'pet:board' %}" class="btn-get-started"
            style="background-color: #FAAB78; text-shadow: 2px 2px 2px  gray; width: 190px; font-size: 15pt; margin-right: 30px;">둘러보기&nbsp;<img
              src="{% static 'assets\img\paw.png' %}" style="width: 15px; height: 15px;"></img></a>
          <a href="https://dang-bti.netlify.app/" class="btn-get-started"
          style="background-color: #FAAB78; text-shadow: 2px 2px 2px gray; width: 190px; font-size: 15pt;">댕BTI&nbsp;<img
            src="{% static 'assets\img\paw.png' %}" style="width: 15px; height: 15px;"></img></a>
        </div>
      </div>
    </div>
  </section>
  <!-- End Hero Section -->

  <!-- 카드형식 그리드 템플릿 -->
  <main id="content" class="content" role="main">
    <h2 style="text-align: center; text-shadow: 2px 2px 2px #FCF9BE;"><img
      src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img>&nbsp;최근 등록 게시물&nbsp;<img
      src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img></h2>
    <div class="wraps">
      <img src="" class="wrapshadow">
      <!-- 그리드 카드 -->
      <div class="grid">
          {% for post, author in post_list%}
          <div class="grid-item">
            <article class="post">
              <!-- <a href="article.html"><img src="{% static 'assets/img/paw.png' %}" style="width: 365px; height:225px;"></a> -->
              {%if post.8 == 1%}
                {% if post.5 %}
                  <div>
                    <a href="{%url 'pet:post_deatil' post.0%}">
                      <img class="card-img-top" src="/media/{{post.5}}" alt="{{ post.5 }} head image" style="width: 392px; height:225px;" />
                    </a>
                  </div>
                {% else %}
                  <div>
                    <a href="{%url 'pet:post_deatil' post.0%}">
                      <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 392px; height:225px;">
                    </a>
                  </div>
                {%endif%}
              {%elif post.8 == 2%}
                {% if post.5 %}
                  <div>
                    <a href="{%url 'pet:recommend_detail' post.0%}">
                      <img class="card-img-top" src="/media/{{post.5}}" alt="{{ post.5 }} head image" style="width: 392px; height:225px;" />
                    </a>
                  </div>
                {% else %}
                  <div>
                    <a href="{%url 'pet:recommend_detail' post.0%}">
                      <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 392px; height:225px;">
                    </a>
                  </div>
                {%endif%}
              {%else%}
                {% if post.5 %}
                  <div>
                    <a href="{%url 'pet:mybaby_detail' post.0%}">
                      <img class="card-img-top" src="/media/{{post.5}}" alt="{{ post.5 }} head image" style="width: 392px; height:225px;" />
                    </a>
                  </div>
                {% else %}
                  <div>
                    <a href="{%url 'pet:mybaby_detail' post.0%}">
                      <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 392px; height:225px;">
                    </a>
                  </div>
                {%endif%}
              {%endif%}
              <div class="wrapgriditem">
                <header>
                  {%if post.8 == 1%}
                  <h3><a href="{%url 'pet:post_deatil' post.0%}">{{post.1 | truncatechars:25}} </a></h3>
                  {%elif post.8 == 2%}
                  <h3><a href="{%url 'pet:recommend_detail' post.0%}">{{post.1 | truncatechars:25}}</a></h3>
                  {%else%}
                  <h3><a href="{%url 'pet:mybaby_detail' post.0%}">{{post.1 | truncatechars:25}}</a></h3>
                  {%endif%}
                </header>
                <section class="post-excerpt">
                  <p>
                    {{post.2| striptags|  truncatechars:50}} <a class="read-more" href="#"></a>
                  </p>
                </section>
                <footer class="post-meta2">
                  <p href="author.html">{{author}}</p>
                  {%if post.8 == 1%}
                  <img class="author-thumb" src="{% static 'assets/img/dog.png' %}" alt="David" nopin="nopin" />
                  {%elif post.8 == 2%}
                  <img class="author-thumb" src="{% static 'assets/img/cat.png' %}" alt="David" nopin="nopin" />
                  {%else%}
                  <img class="author-thumb" src="{% static 'assets/img/leash-dog.png' %}" alt="David" nopin="nopin" />
                  {%endif%}
                  <p class="post-date">{{post.3}}</p>
                </footer>
              </div>
            </article>
          </div>
          {%endfor%}
      </div>
    </div>
  </main>
  <hr>

  <main id="content" class="content" role="main">
    <h2 style="text-align: center; text-shadow: 2px 2px 2px #FCF9BE;"><img
      src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img>&nbsp;뉴스&nbsp;<img
      src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img></h2>
    <div class="wraps">
      <img src="" class="wrapshadow">
      <!-- 그리드 카드 -->
      <div class="grid">
        {% for news in news_list%}
          <div class="grid-item">
            <article class="post">
              <!-- <a href="article.html"><img src="{% static 'assets/img/paw.png' %}" style="width: 365px; height:225px;"></a> -->
              {%if news.news_top_image%}
                  <div>
                    <a href="{{news.get_absolute_url}}">
                      <img class="card-img-top" src="{{ news.news_top_image }}" alt=" head image" style="width: 392px; height:225px;" />
                    </a>
                  </div>
                  {%else%}
                  <div>
                    <a href="{{news.get_absolute_url}}">
                      <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 392px; height:225px;">
                    </a>
                  </div>
                  {%endif%}
              <div class="wrapgriditem">
                <header>
                  <h4><a href="{{news.get_absolute_url}}">{{news.news_title|linebreaks|truncatechars:30}}</a></h4>
                </header>
                <section class="post-excerpt">
                  <p>
                    <img class="author-thumb" src="{% static 'assets/img/sheep-1.png' %}" alt="David" nopin="nopin" />
                  </p>
                  <p class="post-date" id = "post_create">{{news.news_udate}}</p>
                </section>
              </div>
            </article>
          </div>
          {%endfor%}
        </div>
      </div>
    </main>


    <main id="content" class="content" role="main">
    <h2 style="text-align: center; text-shadow: 2px 2px 2px #FCF9BE;;"><img
      src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img>&nbsp;호텔 리스트&nbsp;<img
      src="{% static 'assets\img\paw.png' %}" style="width: 25px; height: 25px;"></img></h2>
    <div class="wraps">
      <img src="" class="wrapshadow">
      <!-- 그리드 카드 -->
      <div class="grid">
        {% for hotel in hotel_list%}
          <div class="grid-item">
            <article class="post">
              <!-- <a href="article.html"><img src="{% static 'assets/img/paw.png' %}" style="width: 365px; height:225px;"></a> -->
              {%if hotel.kh_img_url%}
                  <div>
                    <a href="https://www.booking.com/{{koreahotel.kh_hotel_link }}">
                      <img class="card-img-top" src="{{ hotel.kh_img_url }}" alt=" head image" style="width: 392px; height:225px;" />
                    </a>
                  </div>
                  {%else%}
                  <div>
                    <a href="https://www.booking.com/{{koreahotel.kh_hotel_link }}">
                      <img class="img-fluid post-thumb " src="{%static 'assets\img\gallery\1111.jpg'%}" alt="image" style="width: 392px; height:225px;">
                    </a>
                  </div>
                  {%endif%}
              <div class="wrapgriditem">
                <header>
                  <h4><a href="https://www.booking.com/{{koreahotel.kh_hotel_link }}">{{hotel.kh_hotel_name|linebreaks|truncatewords:10}}</a></h4>
                </header>
                <section class="post-excerpt">
                    <p style="width: 300px; font-size: 20px;" ><i class="bi bi-star-fill" style="font-size: 20pt;"></i>&nbsp;&nbsp;{{hotel.kh_hotel_score|truncatewords:4}}</p>
                    <p style="width: 300px; margin-top: 20px; font-size: 20px;"><i class="bi bi-geo-alt-fill" style="font-size: 20pt;"></i>&nbsp;{{hotel.kh_hotel_location|truncatewords:4}}</p>
                </section>
              </div>
            </article>
          </div>
          {%endfor%}
        </div>
      </div>
    </main>
    
  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>
  <script>

    {% for news in news_list %}
      if ("{{news.news_udate}}" == "None"){
        var news_create = document.querySelectorAll("p#post_create")[{{forloop.counter0}}]
        news_create.innerHTML = "날짜 정보 없음"
      }
    {%endfor%}

    window.onload = function (){
      var news_create = document.getElementById("post_create")
      console.log(news_create)
    }
  </script>
  {% endblock main_area%}

templates/navbar.html
{% load static %}
<script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top" style="background-color: #FAAB78; z-index: 1001;">
    <div class="container-fluid d-flex align-items-center justify-content-between">

        <a href="/" class="logo d-flex align-items-center  me-auto me-lg-0">
            <img src="{% static 'assets\img\favicon.png' %}" style="margin-left: 50px; width: 40px; height: 40px; filter: drop-shadow(2px 2px 2px gray);"></img>
            <h1 style="font-weight: bold; text-shadow: 2px 2px 2px gray;">멍멍냥냥</h1>
        </a>

            <nav id="navbar" class="navbar" style="margin-right: 30px; margin-left: 20px; font-weight: bold;">
                <ul>
                    <li>
                        <a href="{% url 'pet:board' %}"><img src="{% static 'assets\img\dog.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;정보공유</a>
                    </li>
                    <li class="dropdown"><a href="{% url 'pet:recommend' %}"><img src="{% static 'assets\img\cat.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;Store</a>
                    </li>
                    <li><a href="{% url 'pet:mybaby' %}"><img src="{% static 'assets\img\leash-dog.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;내새끼 최고야</a></li>
                    <li class="dropdown"><a href="#"><img src="{% static 'assets\img\turtle.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;Maps<i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="{% url 'naver_map_center' %}">보호센터</a></li>
                            <li><a href="{% url 'naver_map' %}">병원</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'pet:news_list' %}"><img src="{% static 'assets\img\sheep-1.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;뉴스</a></li>
                    <li><a href="{% url 'pet:hotel' %}"><img src="{% static 'assets\img\tiger.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;호텔</a></li>
                    <li><a href="{% url 'pet:animal' %}"><img src="{% static 'assets\img\polar-bear.png' %}" style="width: 20px; height: 20px; filter: drop-shadow(2px 2px 2px gray);"></img>&nbsp;보호중인 동물</a></li>
                </ul>
            </nav><!-- navbar -->
            <nav id="navbar" class="navbar" role="button" style="margin-right: 20px;">
                <ul>
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{user.username}}
                        </a>
                        <ul>
                            <li><a href="{%url 'Account:account_view'%}">유저정보</a></li>
                            <li><a href="/accounts/logout/">Log Out</a></li>
                        <ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <!-- Button trigger modal -->
                        <a class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal">Log In</a>
                    </li>
                    {% endif %}
                </ul>                                                                                                      
            </nav>
        <!-- <a role="button" class="btn btn-warning" style="text-align: center; color: white; text-shadow: 2px 2px 2px gray; background-color: #FCF9BE;" type="button" href="login.html">Log In</a> -->
        

        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    </div>

    
</header>

       <!-- Modal -->
       <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">회원가입 / 로그인</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="d-grid gap-2">
                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{%url 'login'%}"><i class="far fa-envelope">
                    </i>&nbsp&nbsp Log in with E-mail</a>
                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{%url 'register'%}"><i class="far fa-envelope">
                    </i>&nbsp&nbsp Sign Up</a>
                </div>
            </div>
            </div>
        </div>
    </div>
<!-- End Header -->